//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicMe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int FriendId { get; set; }
        public bool Friended { get; set; }
        public int ProfileOriginId { get; set; }
        public int ProfileDestinyId { get; set; }
    
        public virtual Profile ProfileDestinySet { get; set; }
        public virtual Profile ProfileOriginSet { get; set; }
    }
}
